#! /usr/bin/env python

import rospy

from row_endpoint_detection import RowEndpointDetection

if __name__ == '__main__':

  rospy.init_node('row_endpoint_detection')

  red = RowEndpointDetection()

  rospy.spin()

