#! /usr/bin/env python

import rospy

#from dynamic_reconfigure.server import Server as DynamicReconfigureServer

from path_following.general_path_following import GeneralPathFollowing
#from path_following.cfg import general_path_following_paramsConfig as ConfigType

if __name__ == '__main__':

  rospy.init_node('general_path_following')

  gpf = GeneralPathFollowing()
#  server = DynamicReconfigureServer(ConfigType, gpf.reconfigure_path)

  rospy.spin()

