
sim_path:
  - y: 0.0
    x: 0.0
  - y: 0.0
    x: 20.0
  - y: -3.0
    x: -20.0
  - y: -3.0
    x: 20.0
  - y: -6.0
    x: -20.0
  - y: -6.0
    x: 20.0
  - y: -9.0
    x: -20.0
  - y: -9.0
    x: 20.0
  - y: -12.0
    x: -20.0
  - y: -12.0
    x: 20.0
  - y: -15.0
    x: -20.0
  - y: -15.0
    x: 20.0
  - y: -18.0
    x: -20.0
  - y: -18.0
    x: 0.0

